### ISSUE TITLE
好好学习网邀请码2020108分享 [实测可用，但不能靠签到无限免费了]

### ISSUE THREAD

**Issue by finggo** [selierlin/Share-SSR-V2ray#16]
感谢selierlin提供的几个网站，我都注册使用了，感觉好好学习网最好用。
### **20200106实测仍可以通过“签到”免费获得流量，但系统会不定期删免费账户，重复申请就可以无限免费用了。如果不想重复申请，2020年1月初实测可用打五折的优惠码是92AJJ5T，用优惠码买“流量套餐”基本上一个月一块五毛，我比较过很多家服务商，一块五毛一个月算是网上付费当中很便宜的了，“按流量买”比“按时间买”便宜很多。**
但selierlin提供提供的地址有的省份上不了。
免翻强备用地址 https://edu.lovess.top/register?aff=75710 可以学着使用vmess通道，和ssr方式不属同一技术路线！
最好用教育邮箱申请，可以获得更多的流量，即带edu.cn edu.com字样的邮箱。普通邮箱也可以注册成功，不需邀请码了。

流量用完时可通过如下操作免费获得流量
"个人中心"〉“签到”  

另外实测selierlin提供的球加速网也比较好用，没墙也不需注册码，每次续期能得到600MB左右的免费流量，但是该服务商的付费项目相对贵。其余的服务商在我这个地区不好用。我个人是用优惠码买好好学习网的一年套餐在用，一年15块，暂时没找到比这个价更低的服务商，仅供大家参考。

**Comment by linhai1** [comment]
发一码

**Comment by finggo** [comment]
邀请码[20200316 ]
DBC9E0AAD5EB
1434D8912267
68B9C36734C5
D4A238536B30
EA8A70AC09B1
EF2354DE618B

**Comment by finggo** [comment]
４月更新两个好好学习的邀请码
7CED429D617B
58DF642F7EFF
