### ISSUE TITLE
windows配置问题请教

### ISSUE THREAD

**Issue by EricKani** [selierlin/Share-SSR-V2ray#23]
你好，

很感谢你的分享，我在不同的系统电脑上都成功配置了“科学上网”工具。但是最近一次配置windows的时候出现了问题，按照过去的流程配置完成后，不能够成功使用google，过去没有遇到过这种问题。

我不太清楚是不是我的windows本身的网络相关的设置有些问题，请问有什么思路可以推荐吗？谢谢！！

Eric

**Comment by selierlin** [comment]
情况有两种，一是你的代理没有配置成功，二是该节点失效了。
目前大部分节点都会出现被q的情况，属于特殊时期，如果是节点失效也算正常

**Comment by EricKani** [comment]
@selierlin 谢谢你的回复，我上次的问题是我的I（i大写）和l（小写L）没区分开。但是最近确实发现端口经常被屏蔽，每天都会发现头天新改的端口就不能用了。。。幸好ip没有给我封了，不然又是50+块钱。。

**Comment by selierlin** [comment]
这个q严不严也没有个规律，大概就是发生一些大事件或者大日子的时候会这样，一般在电报群里会有讨论，一些机场群总会讨论的

**Comment by SFUMECJF** [comment]
如何清楚其他代理工具产生的影响呢
