### ISSUE TITLE
速蛙跑路了= =

### ISSUE THREAD

**Issue by xiaoas** [selierlin/Share-SSR-V2ray#46]
希望能更新一下 [1-share-ssr-v2ray.md](https://github.com/selierlin/Share-SSR-V2ray/blob/5ebd37f435164dcfa2049a0c32b651fe169cf806/1-share-ssr-v2ray.md)

**Comment by selierlin** [comment]
感谢反馈,已更新

**Comment by WilsonAir** [comment]
邮件已收到，感谢您的来信，我将尽快给您回复。魏后胜I have received your email. Thank you for your letter. I will reply to you as soon as possible.Housheng Wei
