### ISSUE TITLE
好好学习的邀请码提示无效

### ISSUE THREAD

**Issue by fjyuqiang** [selierlin/Share-SSR-V2ray#5]

**Comment by finggo** [comment]
试试吧
DBC9E0AAD5EB
1434D8912267
68B9C36734C5
D4A238536B30
EA8A70AC09B1
EF2354DE618B

**Comment by finggo** [comment]
好好学习网4月20日实测不用邀请码了，50off.edu.cn教育用户专享5折； 30off  7折优惠码 
申请地址：https://edu.lovess.top/register?aff=75710  我自己在用五折优惠码，平均每月一块几毛钱。

**Comment by JxuHenry** [comment]
请问新地址有么？原来的地址无效了

**Comment by Chenzhuoyuee** [comment]
求个新地址 ><

**Comment by Chenzhuoyuee** [comment]
> 好好学习网5月20日更新注册邀请码90D342D3C502；七折优惠码：30off
> 申请地址：[https](https://vip.600mbps.xyz/register?aff=75710) ://vip.600mbps.xyz/register?aff [=](https://vip.600mbps.xyz/register?aff=75710) 75710 我自己有学校的邮箱申请用五折优惠码“按流量购买”一年，平均每月一块几毛钱。试用
> 是不收费的，不断的找免费的用，找烦了才选到这家的，几乎是收费服务商中最便宜的一家。了快一年，还算稳定。

求个新地址 ><
