### ISSUE TITLE
机场推荐

### ISSUE THREAD

**Issue by snivm** [selierlin/Share-SSR-V2ray#90]

**Comment by Lishengcheng651** [comment]
你家机场用不了，网址打不开




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月26日(星期六) 晚上11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [selierlin/Share-SSR-V2ray] 机场推荐 (Issue #90)














 
Closed #90 as completed.

**Comment by alixiaodi** [comment]
> 你家机场用不了，网址打不开
> […](#)

好用还便宜 https://www.freebb.me/#/register?code=NFbalWrF
